### PR TITLE
Fix migrator

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

A few small changes needed:
 - add make to build deps
 - add  `--disable-dependency-tracking` to the configure command

closes #13

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
I'm not sure what is wrong with Drone..

**Comment by jjhelmus** [comment]
> I'm not sure what is wrong with Drone..
We saw a similar issue with Drone last night in the middle of building Python 3.8.0.  I believe Drone changed some settings yesterday which will require a few changes to our setup.  @mariusvniekerk seemed to have a handle on what was need and can provide more details.

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
Hmm. giflib is available for aarch64 but only version 5.1.9.

@isuruf What's the best route here? Build an older 5.1.7 version of giflib, or update this recipe to use a newer giflib?

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
