### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by CurtLH**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CurtLH** [comment]
@conda-forge-admin, please rerender

**Comment by CurtLH** [comment]
Rerendered recipe as directed in `tesseract` [PR](https://github.com/conda-forge/tesseract-feedstock/pull/1)

**Comment by isuruf** [comment]
@msarahan, do you know why libwebp is not detected as a used variable here?

**Comment by isuruf** [comment]
@CurtLH, can you remove trailing whitespaces in the meta.yaml file and rerender?

There's a bug in conda-build when there's trailing whitespaces

**Comment by CurtLH** [comment]
[It's building now](https://github.com/conda-forge/leptonica-feedstock/pull/5)

**Pull request merged**
