### PR TITLE
V1.8

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@izahn, please consider adding yourself as a maintainer if you are willing.  And ping me once the Win and OSX builds are working.  It would be wonderful to have this update!

**Comment by izahn** [comment]
This PR fixes the 1.8 update and adds me  (@izahn) as a maintainer. Ready for review @CurtLH @xylar

**Comment by xylar** [comment]
@izahn, fantastic!  Unless @CurtLH has some feedback, I'll merge this tomorrow morning.

**Comment by xylar** [comment]
Oops, I caught too late that we should have rerendered.  I'll do a dummy PR just for that.

**Pull request merged**
