### PR TITLE
Added build shared libraries by default (.DLL) and bump build number.

### PR DESCRIPTION
**Pull request by joseavegaa**
Added the build of shared libraries (.DLL) by default, as dependencies such as Tesseract need that to be able to link on Windows. Also bumped the build number as there was no version change. 

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by joseavegaa** [comment]
@izahn 

I have successfully added the automatic build of the leptonica-X.XX.X.dll, which will fix the bug in [tesseract-feedstock](https://github.com/conda-forge/tesseract-feedstock/pull/41) in which Leptonica had to be pinned down to version 1.78.0.

It seems that since [this commit](https://github.com/conda-forge/leptonica-feedstock/commit/c65134684b25ddc69abe8a5b6060715519feb1ca), the generator for cmake was change from `%CMAKE_GENERATOR%` to `NMake Makefiles`, and the version of Leptonica at the time was 1.78.0. The change of generator implied that no .DLL was created. 

Once this PR is approved, I'll continue the work in PR#41 in tesseract-feedstock to unpin leptonica and update it after 3 years. 

Let me know if there is something else, thanks.

**Comment by izahn** [comment]
This looks good to me in principle, can you rebase on current main branch @joseavegaa ?

**Comment by joseavegaa** [comment]
Rebase against current main branch has been completed. Let me know if you need something else 👍🏼

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
Thank you for your contribution @joseavegaa !

**Pull request merged**
